void buzzer_init()
{
  pinMode(buzzer, OUTPUT); // Set buzzer - pin 9 as an output
  digitalWrite(buzzer, HIGH); // Send 1KHz sound signal...
  delay(200);        // ...for 1 sec
  digitalWrite(buzzer, LOW);     // Stop sound...
  delay(100);        // ...for 1sec
  digitalWrite(buzzer, HIGH); // Send 1KHz sound signal...
  delay(200);        // ...for 1 sec
  digitalWrite(buzzer, LOW);     // Stop sound...
  delay(100);        // ...for 1sec
  digitalWrite(buzzer, HIGH); // Send 1KHz sound signal...
  delay(200);        // ...for 1 sec
  digitalWrite(buzzer, LOW);     // Stop sound...
}

void buzzer_success()
{
  digitalWrite(buzzer, HIGH); // Send 1KHz sound signal...
  delay(300);        // ...for 1 sec
  digitalWrite(buzzer, LOW);     // Stop sound...
  delay(500);        // ...for 1sec
  digitalWrite(buzzer, HIGH); // Send 1KHz sound signal...
  delay(300);        // ...for 1 sec
  digitalWrite(buzzer, LOW);     // Stop sound...
  delay(50);        // ...for 1sec
  digitalWrite(buzzer, HIGH); // Send 1KHz sound signal...
  delay(300);        // ...for 1 sec
  digitalWrite(buzzer, LOW);     // Stop sound...

}
